port: 8090
# backend:
#   # driver: "pgx"
#   # connection: "root:eATq1GDhsP@tcp(localhost:3306)/idx?&parseTime=true"
driver: "postgres"
connection: "host=localhost user=root password=pass@word1 dbname=idx port=5432 sslmode=disable TimeZone=Asia/Shanghai"
rootgroupname:  "api/v1"
enableoidc: true
policypath: "../policy/rbac_model.conf"
jwtkeyset: "http://localhost:9097/idx/.well-known/jwks"
userendpoint: "http://localhost:9097/idx/oauth2/userinfo"
